---
all:
  children:
    proxmox:
      hosts:
        pve1.ip.cloudyhome.net:
        pve2.ip.cloudyhome.net:
        pve3.ip.cloudyhome.net:
    vm:
      hosts:
        sundarban:
        gorumara:
        simlipal:
        kuldiha:
        pench:
        bandhavgarh:
    ca:
      hosts:
        caserver:
    admin:
      hosts:
        bootstrap.ip.cloudyhome.net:
          ansible_ssh_user: binarycodes
